{% set name = "pyaxiom" %}
{% set version = "1.1.16" %}
{% set build = 0 %}
{% set sha256 = "b2701194df809c0f46e1791554b14100f1c25d0d70580dbd4694e96fae229368" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://github.com/axiom-data-science/pyaxiom/archive/{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: {{ build }}
    script: python setup.py install --single-version-externally-managed --record record.txt
    entry_points:
        - binner=pyaxiom.netcdf.grids.binner:run

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - pytz
        - python-dateutil
        - netcdf4
        - pandas
        - pyncml
        - pynco  # [not win]

test:
    imports:
        - pyaxiom
        - pyaxiom.netcdf
        - pyaxiom.netcdf.grids
        - pyaxiom.netcdf.sensors
        - pyaxiom.tests
    commands:
        - binner --help

about:
    home: https://github.com/axiom-data-science/pyaxiom
    license: MIT License
    summary: An ocean data toolkit developed and used by Axiom Data Science

extra:
    recipe-maintainers:
        - kwilcox
        - ocefpaf
