{% set version = "1.4.6" %}

package:
  name: pyaxiom
  version: {{ version }}

source:
  url: https://github.com/axiom-data-science/pyaxiom/archive/{{ version }}.tar.gz
  sha256: 6770e504db4755f7041d50880c265348f5c443887589a1f2cb8642c026326b5b

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - binner = pyaxiom.netcdf.grids.binner:run

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pytz
    - python-dateutil
    - netcdf4
    - pandas
    - pyncml
    - pynco
    - simplejson

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyaxiom
    - pyaxiom.netcdf
    - pyaxiom.netcdf.grids
    - pyaxiom.netcdf.sensors
  commands:
    - binner --help

about:
  home: https://github.com/axiom-data-science/pyaxiom
  license: MIT
  license_file: LICENSE.txt
  summary: 'An ocean data toolkit developed and used by Axiom Data Science.'

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
