travis:
  secure:
    BINSTAR_TOKEN: Wod97DFunQqShZA0f2Z/S0F7+b5V1Z4vgsBAqkY10bezuCGvrKLU9lPqG1XAbNFuUBdq4O9vimVHs/K8UyTKBZYFCUxaht/OtHy9fo9CQurMUpX0REAxyGZGVeHq2AtWKWHQD8tsKsGivhhF0L4KehZ1RxXynrC10y0oKosRl9nXk3PrTV5bOLCYlx7WlutfeicJmAgbkK0NAbbUINjchv3m+LMvQuxcIdAqQEg6Rojm7CbvayuVUji6WeXXYyX81lx+05IHGgvJj4/l7czLiVKyR6jqkMI3sDAMcIKUkaVhCTECskUkvi73vpzd+JV2oO6LSFilb+tlkP9hxPFz4u05pVAGZ6tYDp6X0zuluueP2YCQ1nT77NECal/tSoqENFKpfKww1nMWKKLNkg2bzxyTq62Of91ZLm2uOtiNGzFLY2s7X88lkmJ2XBxJ4kBug4ONDEmmKV3Lai/y23k5g8b1QHRh6ZiYAH2Da+012S/tphISTO/esgcVny/3jLx59ZNBtLH7O7N1pohA3G7+9zJwHZBVAPgxFOOMfu2Fw4NtBwI2PRhaH7Av2TWj1fBv9snOWlZ2uw7yIi4osRU3wS/gjNkCUbfPDsPrIl4LHPYrI3/Q3b8NI+yy1WSe8DRl7AWQreHfq7Ue/YsKEqyy5gYiizLG2xu8ZOpkLABkZXI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
