travis:
  secure:
    BINSTAR_TOKEN: WLXwirDRUqw2kA1FulwLnqNSfapGu8l8YJE8Ta7ITsFLf27qv1rXNNqLMDHCVIYcOH2G2E7DyPNsAK5z0q09fkZJ4SDAueuW2OShVS+K1SwUYgzZnTxbpiPwaJLGprUB/H9055lOXWnXQ7BDFJtxQMpyK6F9gvo5wsDFmt/JKYnabQBjBPSYtVUq2WPTSinO2OUJYIRahTa0fu01i63ziNG9dqgIj05MmBdgI6nNEAh8IM8DWT/j0JsK0v3tvqwFYr5fSR5a6W8cX1lXMVcoC+WhXaUjPgJBJdSPiTQMyxEl8BY2p9Ko3I+besb3xFhXXAlc5YSa5mghm3IqgnUpPUb0JhEahaJ5a4+hdyTnD0mB170NzH3RT1Ct2M4mWWJGDcabU5oUqlhLFVcmDrVafjLPlFN741vfnZ/7OkcMc4eUdcL8aZr0+amHInhCNlxPx0B6kALLc6iEgu8h1961fvoLU8eilI1v68ckEqWW5M7MH2UJcBC9y+9oyoIf5UrxcYEOrIaFdDVjtSq+UgAXE8uNsmFfEvzuzjXT9wFTrPVKN81WqDHxlKaq7VO4wPDoX80bWvOHso9lXIL8pZssJYDvcygbD/qqVE/XjPm2gqY4LZwFS2j2MEMYNYrXrzTOtpUo944rssgQtkjdbEXPnKV47K9153s4qO/AZFo1Ixg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
